analyzer:
  errors:
    prefer_const_constructors: ignore
    camel_case_types: ignore
    avoid_unnecessary_containers: ignore
    depend_on_referenced_packages: ignore
    file_names: ignore
    deprecated_member_use: ignore
    non_constant_identifier_names: ignore
    unused_field: ignore
    unnecessary_brace_in_string_interps: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Prefer single quotes for consistency
    prefer_single_quotes: false

    # Avoid using print for logging (use debugPrint or logging package instead)
    avoid_print: false

    # Require final for local variables if they are not reassigned
    prefer_final_locals: false

    # Require const constructors where possible
    prefer_const_constructors: false

    # Avoid unnecessary null checks
    unnecessary_null_checks: false



    # Avoid using dynamic when a type can be specified
    avoid_dynamic_calls: false

    # Encourage using collection-if and collection-for
    prefer_collection_literals: false

    # Require specifying return types on functions and methods
    always_declare_return_types: false
